use {
    crate::types::{Idl, IdlCodec, IdlPdaSeed, IdlResolver, IdlType, IdlTypeDef},
    quasar_schema::pascal_to_snake,
    std::{collections::HashMap, fmt::Write},
};

/// Generate a C client header from the IDL.
///
/// Produces a single header depending on `caravel.h` for Pubkey, AccountMeta,
/// and Instruction.
pub fn generate_c_client(idl: &Idl) -> String {
    let prefix = idl.metadata.client_name(&idl.name).replace('-', "_");
    let guard = format!("{}_CLIENT_H", prefix.to_ascii_uppercase());
    let mut out = String::new();

    writeln!(out, "/* Code generated by quasar. DO NOT EDIT. */").unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}\n").unwrap();
    writeln!(out, "#include <caravel.h>\n").unwrap();

    emit_program_id(&mut out, &prefix, &idl.address);
    emit_discriminators(&mut out, &prefix, idl);
    emit_type_defs(&mut out, &prefix, &idl.types);
    emit_decode_fns(&mut out, &prefix, &idl.types);
    emit_instructions(&mut out, &prefix, idl);
    emit_error_codes(&mut out, &prefix, &idl.errors);

    writeln!(out, "#endif /* {guard} */").unwrap();
    out
}

fn emit_program_id(out: &mut String, prefix: &str, address: &str) {
    let upper = prefix.to_ascii_uppercase();
    let bytes = bs58::decode(address).into_vec().unwrap_or_default();
    write!(out, "static const Pubkey {upper}_PROGRAM_ID = {{{{").unwrap();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}").unwrap();
    }
    out.push_str("\n}};\n\n");
}

fn emit_discriminators(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let name = pascal_to_snake(&ix.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_DISC[] = {{{}}};",
            super::format_disc_hex(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = pascal_to_snake(&acc.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_ACCOUNT_DISC[] = {{{}}};",
            super::format_disc_hex(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = pascal_to_snake(&ev.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_EVENT_DISC[] = {{{}}};",
            super::format_disc_hex(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }
}

fn emit_type_defs(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        let snake = pascal_to_snake(&td.name);
        writeln!(out, "typedef struct {{").unwrap();
        if td.fields.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for field in &td.fields {
            emit_struct_field(out, prefix, &field.name, &field.ty, field.codec.as_ref());
        }
        writeln!(out, "}} {prefix}_{snake}_t;\n").unwrap();
    }
}

fn emit_decode_fns(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        if td.fields.is_empty() {
            continue;
        }
        let snake = pascal_to_snake(&td.name);
        writeln!(
            out,
            "static inline void {prefix}_{snake}_decode(\n    const uint8_t *data, \
             {prefix}_{snake}_t *out\n) {{",
        )
        .unwrap();
        writeln!(out, "    uint64_t offset = 0;").unwrap();
        for field in &td.fields {
            out.push_str(&decode_field_expr(
                &field.name,
                &field.ty,
                field.codec.as_ref(),
                1,
                types,
            ));
        }
        out.push_str("}\n\n");
    }
}

fn emit_instructions(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let ix_snake = pascal_to_snake(&ix.name);
        let user_accounts: Vec<_> = ix
            .accounts
            .iter()
            .filter(|a| !matches!(a.resolver, IdlResolver::Pda { .. }))
            .collect();
        let account_field_seeds = account_field_seed_inputs(ix);

        writeln!(out, "typedef struct {{").unwrap();
        for acc in &user_accounts {
            writeln!(out, "    Pubkey *{};", acc.name).unwrap();
        }
        for (path, field) in &account_field_seeds {
            let name = account_field_seed_input_name(path, field);
            writeln!(out, "    const uint8_t *{name};").unwrap();
            writeln!(out, "    uint64_t {name}_len;").unwrap();
        }
        if user_accounts.is_empty() && account_field_seeds.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        writeln!(out, "}} {prefix}_{ix_snake}_accounts_t;\n").unwrap();

        let has_args = !ix.args.is_empty();
        writeln!(out, "typedef struct {{").unwrap();
        if !has_args {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for arg in &ix.args {
            emit_struct_field(out, prefix, &arg.name, &arg.ty, arg.codec.as_ref());
        }
        writeln!(out, "}} {prefix}_{ix_snake}_args_t;\n").unwrap();

        let disc_len = ix.discriminator.len();
        let num_accounts = ix.accounts.len();
        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "static inline uint64_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    const AccountMeta *remaining,\n    uint64_t remaining_len,\n    \
                 Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint8_t *data_buf,\n    \
                 uint64_t data_buf_len\n) {{",
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "static inline uint64_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint8_t \
                 *data_buf,\n    uint64_t data_buf_len\n) {{",
            )
            .unwrap();
        }

        let pda_count = ix
            .accounts
            .iter()
            .filter(|a| matches!(a.resolver, IdlResolver::Pda { .. }))
            .count();
        if pda_count > 0 {
            writeln!(out, "    Pubkey pda_keys[{pda_count}];").unwrap();
        }

        let mut pda_name_to_idx: HashMap<&str, usize> = HashMap::new();
        {
            let mut idx = 0usize;
            for acc in &ix.accounts {
                if matches!(acc.resolver, IdlResolver::Pda { .. }) {
                    pda_name_to_idx.insert(acc.name.as_str(), idx);
                    idx += 1;
                }
            }
        }

        // derive pdas
        let mut pda_idx = 0usize;
        for acc in &ix.accounts {
            if let IdlResolver::Pda { ref seeds, .. } = acc.resolver {
                emit_pda_derivation(out, seeds, &upper, pda_idx, &pda_name_to_idx);
                pda_idx += 1;
            }
        }

        // build account metas
        pda_idx = 0;
        for (i, acc) in ix.accounts.iter().enumerate() {
            let key_expr = if matches!(acc.resolver, IdlResolver::Pda { .. }) {
                let expr = format!("&pda_keys[{pda_idx}]");
                pda_idx += 1;
                expr
            } else {
                format!("accounts->{}", acc.name)
            };

            let helper = meta_helper(acc.writable.is_true(), acc.signer.is_true());
            writeln!(out, "    meta_buf[{i}] = {helper}({key_expr});").unwrap();
        }

        // serialize data
        writeln!(out, "    uint64_t off = 0;").unwrap();
        let args_overhead: usize = ix
            .args
            .iter()
            .map(|a| static_data_overhead(&a.ty, a.codec.as_ref(), &idl.types))
            .sum();
        let min_data = disc_len + args_overhead;
        writeln!(out, "    if (data_buf_len < {min_data}) return 0;").unwrap();
        writeln!(
            out,
            "    for (uint64_t i = 0; i < {disc_len}; i++) data_buf[off++] = \
             {upper}_{ix_upper}_DISC[i];",
            ix_upper = ix_snake.to_ascii_uppercase(),
        )
        .unwrap();
        if has_args {
            for arg in &ix.args {
                out.push_str(&serialize_field_expr(
                    &format!("args->{}", arg.name),
                    &arg.ty,
                    arg.codec.as_ref(),
                    &idl.types,
                    1,
                ));
            }
        }

        // append remaining accounts
        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[{num_accounts} + i] = \
                 remaining[i];"
            )
            .unwrap();
        }

        // assemble instruction
        writeln!(
            out,
            "    ix_out->program_id = (Pubkey *)&{upper}_PROGRAM_ID;"
        )
        .unwrap();
        writeln!(out, "    ix_out->accounts = meta_buf;").unwrap();
        if ix.remaining_accounts.is_some() {
            writeln!(
                out,
                "    ix_out->accounts_len = {num_accounts} + remaining_len;"
            )
            .unwrap();
        } else {
            writeln!(out, "    ix_out->accounts_len = {num_accounts};").unwrap();
        }
        writeln!(out, "    ix_out->data = data_buf;").unwrap();
        writeln!(out, "    ix_out->data_len = off;").unwrap();
        writeln!(out, "    return off;").unwrap();
        out.push_str("}\n\n");
    }
}

fn meta_helper(writable: bool, signer: bool) -> &'static str {
    match (writable, signer) {
        (true, true) => "meta_writable_signer",
        (true, false) => "meta_writable",
        (false, true) => "meta_readonly_signer",
        (false, false) => "meta_readonly",
    }
}

fn emit_pda_derivation(
    out: &mut String,
    seeds: &[IdlPdaSeed],
    upper_prefix: &str,
    pda_idx: usize,
    pda_name_to_idx: &HashMap<&str, usize>,
) {
    let seed_count = seeds.len();
    writeln!(out, "    {{").unwrap();
    writeln!(out, "        SignerSeed seeds[{seed_count}];").unwrap();
    for (i, seed) in seeds.iter().enumerate() {
        match seed {
            IdlPdaSeed::Const { value } => {
                let hex = super::format_disc_hex(value);
                let len = value.len();
                writeln!(
                    out,
                    "        {{ static const uint8_t s[] = {{{hex}}}; seeds[{i}].addr = s; \
                     seeds[{i}].len = {len}; }}"
                )
                .unwrap();
            }
            IdlPdaSeed::Account { path } => {
                if let Some(&ref_idx) = pda_name_to_idx.get(path.as_str()) {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = pda_keys[{ref_idx}].bytes; seeds[{i}].len = 32;"
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = accounts->{path}->bytes; seeds[{i}].len = 32;"
                    )
                    .unwrap();
                }
            }
            IdlPdaSeed::AccountField { path, field, .. } => {
                let name = account_field_seed_input_name(path, field);
                writeln!(
                    out,
                    "        seeds[{i}].addr = accounts->{name}; seeds[{i}].len = \
                     accounts->{name}_len;"
                )
                .unwrap();
            }
            IdlPdaSeed::Arg { path, .. } => {
                writeln!(
                    out,
                    "        seeds[{i}].addr = (const uint8_t *)&args->{path}; seeds[{i}].len = \
                     sizeof(args->{path});"
                )
                .unwrap();
            }
        }
    }
    writeln!(out, "        uint8_t bump;").unwrap();
    writeln!(
        out,
        "        find_program_address(seeds, {seed_count}, (Pubkey *)&{upper_prefix}_PROGRAM_ID, \
         &pda_keys[{pda_idx}], &bump);"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
}

fn account_field_seed_inputs(ix: &crate::types::IdlInstruction) -> Vec<(String, String)> {
    let mut inputs = Vec::new();
    for acc in &ix.accounts {
        let IdlResolver::Pda { seeds, .. } = &acc.resolver else {
            continue;
        };
        for seed in seeds {
            let IdlPdaSeed::AccountField { path, field, .. } = seed else {
                continue;
            };
            if !inputs
                .iter()
                .any(|(seen_path, seen_field)| seen_path == path && seen_field == field)
            {
                inputs.push((path.clone(), field.clone()));
            }
        }
    }
    inputs
}

fn account_field_seed_input_name(path: &str, field: &str) -> String {
    format!(
        "{}_{}_seed",
        path,
        field.split('.').collect::<Vec<_>>().join("_")
    )
}

fn emit_error_codes(out: &mut String, prefix: &str, errors: &[crate::types::IdlErrorDef]) {
    if errors.is_empty() {
        return;
    }
    let upper = prefix.to_ascii_uppercase();
    for err in errors {
        let name = err.name.to_ascii_uppercase();
        writeln!(out, "#define {upper}_ERR_{name} {code}", code = err.code).unwrap();
    }
    out.push('\n');
}

fn c_type(ty: &IdlType, prefix: &str) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => "bool".into(),
            "u8" => "uint8_t".into(),
            "i8" => "int8_t".into(),
            "u16" => "uint16_t".into(),
            "i16" => "int16_t".into(),
            "u32" => "uint32_t".into(),
            "i32" => "int32_t".into(),
            "u64" => "uint64_t".into(),
            "i64" => "int64_t".into(),
            "u128" | "i128" => "uint8_t".into(),
            "f32" => "float".into(),
            "f64" => "double".into(),
            "pubkey" => "Pubkey".into(),
            "string" => "uint8_t *".into(),
            _ => "uint8_t *".into(),
        },
        IdlType::Option { option } => c_type(option, prefix),
        IdlType::Vec { .. } => "uint8_t *".into(),
        IdlType::Array {
            array: (_inner, size),
        } => format!("uint8_t[{size}]"),
        IdlType::Defined { defined } => {
            format!("{prefix}_{}_t", pascal_to_snake(&defined.name))
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn is_fixed_array_type(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Array { .. })
}

fn fixed_array_size(ty: &IdlType) -> usize {
    match ty {
        IdlType::Array {
            array: (_inner, size),
        } => *size,
        _ => 1,
    }
}

fn is_128bit(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Primitive(p) if p == "u128" || p == "i128")
}

fn is_dynamic_with_codec(ty: &IdlType, codec: Option<&IdlCodec>) -> bool {
    match ty {
        IdlType::Primitive(p) if p == "string" && codec.is_some() => true,
        IdlType::Vec { .. } if codec.is_some() => true,
        _ => false,
    }
}

fn emit_struct_field(
    out: &mut String,
    prefix: &str,
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
) {
    let (is_opt, inner, inner_codec) = match ty {
        IdlType::Option { option } => (true, option.as_ref(), None),
        other => (false, other, codec),
    };
    if is_opt {
        writeln!(out, "    bool {name}_present;").unwrap();
    }
    if is_dynamic_with_codec(inner, inner_codec) {
        writeln!(out, "    const uint8_t *{name};").unwrap();
        writeln!(out, "    uint32_t {name}_len;").unwrap();
    } else if is_fixed_array_type(inner) {
        let size = fixed_array_size(inner);
        writeln!(out, "    uint8_t {name}[{size}];").unwrap();
    } else if is_128bit(inner) {
        writeln!(out, "    uint8_t {name}[16];").unwrap();
    } else {
        writeln!(out, "    {} {name};", c_type(inner, prefix)).unwrap();
    }
}

fn static_data_overhead(ty: &IdlType, codec: Option<&IdlCodec>, types: &[IdlTypeDef]) -> usize {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" | "u8" | "i8" => 1,
            "u16" | "i16" => 2,
            "u32" | "i32" | "f32" => 4,
            "u64" | "i64" | "f64" => 8,
            "u128" | "i128" => 16,
            "pubkey" => 32,
            "string" => {
                if let Some(c) = codec {
                    c.prefix_bytes()
                } else {
                    4 // borsh-style u32 prefix
                }
            }
            _ => 0,
        },
        IdlType::Option { option } => 1 + static_data_overhead(option, None, types),
        IdlType::Defined { defined } => types
            .iter()
            .find(|t| t.name == defined.name)
            .map(|td| {
                td.fields
                    .iter()
                    .map(|f| static_data_overhead(&f.ty, f.codec.as_ref(), types))
                    .sum()
            })
            .unwrap_or(0),
        IdlType::Vec { .. } => {
            if let Some(c) = codec {
                c.prefix_bytes()
            } else {
                4 // borsh-style u32 prefix
            }
        }
        IdlType::Array {
            array: (_inner, size),
        } => *size,
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn serialize_dyn_bytes(name: &str, prefix_bytes: usize, t: &str) -> String {
    let pb = prefix_bytes;
    let write_prefix = match prefix_bytes {
        1 => format!("{t}data_buf[off++] = (uint8_t){name}_len;\n"),
        2 => format!(
            "{t}{{ uint16_t slen = (uint16_t){name}_len; data_buf[off] = (uint8_t)slen; \
             data_buf[off+1] = (uint8_t)(slen >> 8); off += 2; }}\n"
        ),
        4 => format!(
            "{t}{{ uint32_t slen = {name}_len; data_buf[off] = (uint8_t)slen; data_buf[off+1] = \
             (uint8_t)(slen >> 8); data_buf[off+2] = (uint8_t)(slen >> 16); data_buf[off+3] = \
             (uint8_t)(slen >> 24); off += 4; }}\n"
        ),
        _ => format!(
            "{t}{{ uint64_t slen = (uint64_t){name}_len; for (int i = 0; i < 8; i++) {{ \
             data_buf[off + i] = (uint8_t)(slen >> (i * 8)); }} off += 8; }}\n"
        ),
    };
    format!(
        "{t}if (off + {pb} + {name}_len > data_buf_len) return 0;\n{write_prefix}{t}for (uint32_t \
         i = 0; i < {name}_len; i++) data_buf[off++] = {name}[i];\n"
    )
}

fn decode_dyn_bytes(name: &str, prefix_bytes: usize, t: &str) -> String {
    match prefix_bytes {
        1 => format!(
            "{t}out->{name}_len = data[offset]; offset += 1;\n{t}out->{name} = &data[offset]; \
             offset += out->{name}_len;\n"
        ),
        2 => format!(
            "{t}out->{name}_len = (uint32_t)((uint16_t)data[offset] | ((uint16_t)data[offset+1] \
             << 8)); offset += 2;\n{t}out->{name} = &data[offset]; offset += out->{name}_len;\n"
        ),
        4 => format!(
            "{t}out->{name}_len = (uint32_t)data[offset] | ((uint32_t)data[offset+1] << 8) | \
             ((uint32_t)data[offset+2] << 16) | ((uint32_t)data[offset+3] << 24); offset += \
             4;\n{t}out->{name} = &data[offset]; offset += out->{name}_len;\n"
        ),
        _ => format!(
            "{t}{{ uint64_t dlen = 0; for (int i = 0; i < 8; i++) dlen |= \
             ((uint64_t)data[offset+i]) << (i*8); offset += 8; out->{name}_len = (uint32_t)dlen; \
             out->{name} = &data[offset]; offset += out->{name}_len; }}\n"
        ),
    }
}

fn serialize_field_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    types: &[IdlTypeDef],
    indent: usize,
) -> String {
    let t = "    ".repeat(indent);

    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                return serialize_dyn_bytes(name, c.prefix_bytes(), &t);
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { .. } = ty {
        if let Some(c) = codec {
            return serialize_dyn_bytes(name, c.prefix_bytes(), &t);
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}data_buf[off++] = {name} ? 1 : 0;\n"),
            "u8" => format!("{t}data_buf[off++] = {name};\n"),
            "i8" => format!("{t}data_buf[off++] = (uint8_t){name};\n"),
            "u16" => format!(
                "{t}{{ uint16_t v = {name}; data_buf[off] = (uint8_t)v; data_buf[off+1] = \
                 (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "i16" => format!(
                "{t}{{ uint16_t v = (uint16_t){name}; data_buf[off] = (uint8_t)v; data_buf[off+1] \
                 = (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "u32" | "f32" => {
                let cast = if p == "f32" {
                    "uint32_t v; {{ union {{ float f; uint32_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else {
                    format!("uint32_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} data_buf[off] = (uint8_t)v; data_buf[off+1] = (uint8_t)(v >> \
                     8); data_buf[off+2] = (uint8_t)(v >> 16); data_buf[off+3] = (uint8_t)(v >> \
                     24); off += 4; }}\n"
                )
            }
            "u64" | "i64" | "f64" => {
                let cast = if p == "f64" {
                    "uint64_t v; {{ union {{ double f; uint64_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else if p == "i64" {
                    format!("uint64_t v = (uint64_t){name};")
                } else {
                    format!("uint64_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} for (int i = 0; i < 8; i++) {{ data_buf[off + i] = (uint8_t)(v \
                     >> (i * 8)); }} off += 8; }}\n"
                )
            }
            "u128" | "i128" => format!(
                "{t}for (int i = 0; i < 16; i++) data_buf[off + i] = {name}[i]; off += 16;\n"
            ),
            "pubkey" => format!(
                "{t}for (int i = 0; i < 32; i++) data_buf[off + i] = {name}.bytes[i]; off += 32;\n"
            ),
            "string" => {
                // Plain string without codec — u32 prefix (borsh-style)
                serialize_dyn_bytes(name, 4, &t)
            }
            _ => format!("{t}/* unsupported type for {name} */\n"),
        },
        IdlType::Option { option } => {
            let ti = "    ".repeat(indent + 1);
            let inner = serialize_field_expr(name, option, None, types, indent + 1);
            format!(
                "{t}if ({name}_present) {{\n{ti}data_buf[off++] = 1;\n{inner}{t}}} else \
                 {{\n{ti}data_buf[off++] = 0;\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&serialize_field_expr(
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        types,
                        indent,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {} */\n", defined.name)
            }
        }
        IdlType::Vec { .. } => {
            // Vec without codec — u32 prefix (borsh-style)
            serialize_dyn_bytes(name, 4, &t)
        }
        IdlType::Array {
            array: (_inner, size),
        } => {
            format!(
                "{t}for (int i = 0; i < {size}; i++) data_buf[off + i] = {name}[i]; off += \
                 {size};\n"
            )
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}

fn decode_field_expr(
    name: &str,
    ty: &IdlType,
    codec: Option<&IdlCodec>,
    depth: usize,
    types: &[IdlTypeDef],
) -> String {
    let t = "    ".repeat(depth);

    // Handle dynamic string with codec
    if let IdlType::Primitive(p) = ty {
        if p == "string" {
            if let Some(c) = codec {
                return decode_dyn_bytes(name, c.prefix_bytes(), &t);
            }
        }
    }

    // Handle Vec with codec
    if let IdlType::Vec { .. } = ty {
        if let Some(c) = codec {
            return decode_dyn_bytes(name, c.prefix_bytes(), &t);
        }
    }

    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}out->{name} = data[offset] != 0; offset += 1;\n"),
            "u8" => format!("{t}out->{name} = data[offset]; offset += 1;\n"),
            "i8" => format!("{t}out->{name} = (int8_t)data[offset]; offset += 1;\n"),
            "u16" => format!(
                "{t}out->{name} = (uint16_t)data[offset] | ((uint16_t)data[offset + 1] << 8); \
                 offset += 2;\n"
            ),
            "i16" => format!(
                "{t}out->{name} = (int16_t)((uint16_t)data[offset] | ((uint16_t)data[offset + 1] \
                 << 8)); offset += 2;\n"
            ),
            "u32" => format!(
                "{t}out->{name} = (uint32_t)data[offset] | ((uint32_t)data[offset + 1] << 8) | \
                 ((uint32_t)data[offset + 2] << 16) | ((uint32_t)data[offset + 3] << 24); offset \
                 += 4;\n"
            ),
            "i32" => format!(
                "{t}out->{name} = (int32_t)((uint32_t)data[offset] | ((uint32_t)data[offset + 1] \
                 << 8) | ((uint32_t)data[offset + 2] << 16) | ((uint32_t)data[offset + 3] << \
                 24)); offset += 4;\n"
            ),
            "u64" => format!(
                "{t}{{ uint64_t v = 0; for (int i = 0; i < 8; i++) v |= ((uint64_t)data[offset + \
                 i]) << (i * 8); out->{name} = v; offset += 8; }}\n"
            ),
            "i64" => format!(
                "{t}{{ uint64_t v = 0; for (int i = 0; i < 8; i++) v |= ((uint64_t)data[offset + \
                 i]) << (i * 8); out->{name} = (int64_t)v; offset += 8; }}\n"
            ),
            "f32" => format!(
                "{t}{{ union {{ uint32_t u; float f; }} c; c.u = (uint32_t)data[offset] | \
                 ((uint32_t)data[offset+1] << 8) | ((uint32_t)data[offset+2] << 16) | \
                 ((uint32_t)data[offset+3] << 24); out->{name} = c.f; offset += 4; }}\n"
            ),
            "f64" => format!(
                "{t}{{ union {{ uint64_t u; double f; }} c; c.u = 0; for (int i = 0; i < 8; i++) \
                 c.u |= ((uint64_t)data[offset + i]) << (i * 8); out->{name} = c.f; offset += 8; \
                 }}\n"
            ),
            "u128" | "i128" => format!(
                "{t}for (int i = 0; i < 16; i++) out->{name}[i] = data[offset + i]; offset += \
                 16;\n"
            ),
            "pubkey" => format!(
                "{t}for (int i = 0; i < 32; i++) out->{name}.bytes[i] = data[offset + i]; offset \
                 += 32;\n"
            ),
            "string" => {
                // Plain string without codec — u32 prefix (borsh-style)
                decode_dyn_bytes(name, 4, &t)
            }
            _ => format!("{t}/* unsupported decode for {name} */\n"),
        },
        IdlType::Vec { .. } => {
            // Vec without codec — u32 prefix (borsh-style)
            decode_dyn_bytes(name, 4, &t)
        }
        IdlType::Array {
            array: (_inner, size),
        } => {
            format!(
                "{t}for (int i = 0; i < {size}; i++) out->{name}[i] = data[offset + i]; offset += \
                 {size};\n"
            )
        }
        IdlType::Option { option } => {
            let inner = decode_field_expr(name, option, None, depth + 1, types);
            let ti = "    ".repeat(depth + 1);
            format!(
                "{t}if (data[offset] != 0) {{\n{ti}offset += 1;\n{ti}out->{name}_present = \
                 1;\n{inner}{t}}} else {{\n{ti}offset += 1;\n{ti}out->{name}_present = 0;\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == defined.name) {
                let mut result = String::new();
                for field in &td.fields {
                    result.push_str(&decode_field_expr(
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        field.codec.as_ref(),
                        depth,
                        types,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {} */\n", defined.name)
            }
        }
        IdlType::Generic { generic } => {
            panic!("Generic type '{}' not supported in C codegen", generic)
        }
    }
}
