use {
    crate::types::{Idl, IdlSeed, IdlType, IdlTypeDef},
    quasar_schema::pascal_to_snake,
    std::{collections::HashMap, fmt::Write},
};

/// Generate a C client header from the IDL.
///
/// Produces a single header depending on `caravel.h` for Pubkey, AccountMeta,
/// and Instruction.
pub fn generate_c_client(idl: &Idl) -> String {
    let prefix = idl.metadata.client_name().replace('-', "_");
    let guard = format!("{}_CLIENT_H", prefix.to_ascii_uppercase());
    let mut out = String::new();

    writeln!(out, "/* Code generated by quasar. DO NOT EDIT. */").unwrap();
    writeln!(out, "#ifndef {guard}").unwrap();
    writeln!(out, "#define {guard}\n").unwrap();
    writeln!(out, "#include <caravel.h>\n").unwrap();

    emit_program_id(&mut out, &prefix, &idl.address);
    emit_discriminators(&mut out, &prefix, idl);
    emit_type_defs(&mut out, &prefix, &idl.types);
    emit_decode_fns(&mut out, &prefix, &idl.types);
    emit_instructions(&mut out, &prefix, idl);
    emit_error_codes(&mut out, &prefix, &idl.errors);

    writeln!(out, "#endif /* {guard} */").unwrap();
    out
}

fn emit_program_id(out: &mut String, prefix: &str, address: &str) {
    let upper = prefix.to_ascii_uppercase();
    let bytes = bs58::decode(address).into_vec().unwrap_or_default();
    write!(out, "static const Pubkey {upper}_PROGRAM_ID = {{{{").unwrap();
    for (i, b) in bytes.iter().enumerate() {
        if i > 0 {
            out.push_str(", ");
        }
        if i % 8 == 0 {
            out.push_str("\n    ");
        }
        write!(out, "0x{b:02x}").unwrap();
    }
    out.push_str("\n}};\n\n");
}

fn emit_discriminators(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let name = pascal_to_snake(&ix.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_DISC[] = {{{}}};",
            super::format_disc_hex(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = pascal_to_snake(&acc.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_ACCOUNT_DISC[] = {{{}}};",
            super::format_disc_hex(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = pascal_to_snake(&ev.name).to_ascii_uppercase();
        writeln!(
            out,
            "static const uint8_t {upper}_{name}_EVENT_DISC[] = {{{}}};",
            super::format_disc_hex(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }
}

fn emit_type_defs(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        let snake = pascal_to_snake(&td.name);
        writeln!(out, "typedef struct {{").unwrap();
        if td.ty.fields.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for field in &td.ty.fields {
            emit_struct_field(out, prefix, &field.name, &field.ty);
        }
        writeln!(out, "}} {prefix}_{snake}_t;\n").unwrap();
    }
}

fn emit_decode_fns(out: &mut String, prefix: &str, types: &[IdlTypeDef]) {
    for td in types {
        if td.ty.fields.is_empty() {
            continue;
        }
        let snake = pascal_to_snake(&td.name);
        writeln!(
            out,
            "static inline void {prefix}_{snake}_decode(\n    const uint8_t *data, \
             {prefix}_{snake}_t *out\n) {{",
        )
        .unwrap();
        writeln!(out, "    uint64_t offset = 0;").unwrap();
        for field in &td.ty.fields {
            out.push_str(&decode_field_expr(&field.name, &field.ty, 1, types));
        }
        out.push_str("}\n\n");
    }
}

fn emit_instructions(out: &mut String, prefix: &str, idl: &Idl) {
    let upper = prefix.to_ascii_uppercase();

    for ix in &idl.instructions {
        let ix_snake = pascal_to_snake(&ix.name);
        let user_accounts: Vec<_> = ix.accounts.iter().filter(|a| a.pda.is_none()).collect();

        writeln!(out, "typedef struct {{").unwrap();
        for acc in &user_accounts {
            writeln!(out, "    Pubkey *{};", acc.name).unwrap();
        }
        if user_accounts.is_empty() {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        writeln!(out, "}} {prefix}_{ix_snake}_accounts_t;\n").unwrap();

        let has_args = !ix.args.is_empty();
        writeln!(out, "typedef struct {{").unwrap();
        if !has_args {
            writeln!(out, "    uint8_t _pad;").unwrap();
        }
        for arg in &ix.args {
            emit_struct_field(out, prefix, &arg.name, &arg.ty);
        }
        writeln!(out, "}} {prefix}_{ix_snake}_args_t;\n").unwrap();

        let disc_len = ix.discriminator.len();
        let num_accounts = ix.accounts.len();
        if ix.has_remaining {
            writeln!(
                out,
                "static inline uint64_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    const AccountMeta *remaining,\n    uint64_t remaining_len,\n    \
                 Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint8_t *data_buf,\n    \
                 uint64_t data_buf_len\n) {{",
            )
            .unwrap();
        } else {
            writeln!(
                out,
                "static inline uint64_t {prefix}_{ix_snake}_ix(\n    \
                 {prefix}_{ix_snake}_accounts_t *accounts,\n    {prefix}_{ix_snake}_args_t \
                 *args,\n    Instruction *ix_out,\n    AccountMeta *meta_buf,\n    uint8_t \
                 *data_buf,\n    uint64_t data_buf_len\n) {{",
            )
            .unwrap();
        }

        let pda_count = ix.accounts.iter().filter(|a| a.pda.is_some()).count();
        if pda_count > 0 {
            writeln!(out, "    Pubkey pda_keys[{pda_count}];").unwrap();
        }

        let mut pda_name_to_idx: HashMap<&str, usize> = HashMap::new();
        {
            let mut idx = 0usize;
            for acc in &ix.accounts {
                if acc.pda.is_some() {
                    pda_name_to_idx.insert(acc.name.as_str(), idx);
                    idx += 1;
                }
            }
        }

        // derive pdas
        let mut pda_idx = 0usize;
        for acc in &ix.accounts {
            if let Some(ref pda) = acc.pda {
                emit_pda_derivation(out, pda, &upper, pda_idx, &pda_name_to_idx);
                pda_idx += 1;
            }
        }

        // build account metas
        pda_idx = 0;
        for (i, acc) in ix.accounts.iter().enumerate() {
            let key_expr = if acc.pda.is_some() {
                let expr = format!("&pda_keys[{pda_idx}]");
                pda_idx += 1;
                expr
            } else {
                format!("accounts->{}", acc.name)
            };

            let helper = meta_helper(acc.writable, acc.signer);
            writeln!(out, "    meta_buf[{i}] = {helper}({key_expr});").unwrap();
        }

        // serialize data
        writeln!(out, "    uint64_t off = 0;").unwrap();
        let args_overhead: usize = ix
            .args
            .iter()
            .map(|a| static_data_overhead(&a.ty, &idl.types))
            .sum();
        let min_data = disc_len + args_overhead;
        writeln!(out, "    if (data_buf_len < {min_data}) return 0;").unwrap();
        writeln!(
            out,
            "    for (uint64_t i = 0; i < {disc_len}; i++) data_buf[off++] = \
             {upper}_{ix_upper}_DISC[i];",
            ix_upper = ix_snake.to_ascii_uppercase(),
        )
        .unwrap();
        if has_args {
            for arg in &ix.args {
                out.push_str(&serialize_field_expr(
                    &format!("args->{}", arg.name),
                    &arg.ty,
                    &idl.types,
                    1,
                ));
            }
        }

        // append remaining accounts
        if ix.has_remaining {
            writeln!(
                out,
                "    for (uint64_t i = 0; i < remaining_len; i++) meta_buf[{num_accounts} + i] = \
                 remaining[i];"
            )
            .unwrap();
        }

        // assemble instruction
        writeln!(
            out,
            "    ix_out->program_id = (Pubkey *)&{upper}_PROGRAM_ID;"
        )
        .unwrap();
        writeln!(out, "    ix_out->accounts = meta_buf;").unwrap();
        if ix.has_remaining {
            writeln!(
                out,
                "    ix_out->accounts_len = {num_accounts} + remaining_len;"
            )
            .unwrap();
        } else {
            writeln!(out, "    ix_out->accounts_len = {num_accounts};").unwrap();
        }
        writeln!(out, "    ix_out->data = data_buf;").unwrap();
        writeln!(out, "    ix_out->data_len = off;").unwrap();
        writeln!(out, "    return off;").unwrap();
        out.push_str("}\n\n");
    }
}

fn meta_helper(writable: bool, signer: bool) -> &'static str {
    match (writable, signer) {
        (true, true) => "meta_writable_signer",
        (true, false) => "meta_writable",
        (false, true) => "meta_readonly_signer",
        (false, false) => "meta_readonly",
    }
}

fn emit_pda_derivation(
    out: &mut String,
    pda: &crate::types::IdlPda,
    upper_prefix: &str,
    pda_idx: usize,
    pda_name_to_idx: &HashMap<&str, usize>,
) {
    let seed_count = pda.seeds.len();
    writeln!(out, "    {{").unwrap();
    writeln!(out, "        SignerSeed seeds[{seed_count}];").unwrap();
    for (i, seed) in pda.seeds.iter().enumerate() {
        match seed {
            IdlSeed::Const { value } => {
                let hex = super::format_disc_hex(value);
                let len = value.len();
                writeln!(
                    out,
                    "        {{ static const uint8_t s[] = {{{hex}}}; seeds[{i}].addr = s; \
                     seeds[{i}].len = {len}; }}"
                )
                .unwrap();
            }
            IdlSeed::Account { path } => {
                if let Some(&ref_idx) = pda_name_to_idx.get(path.as_str()) {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = pda_keys[{ref_idx}].bytes; seeds[{i}].len = 32;"
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "        seeds[{i}].addr = accounts->{path}->bytes; seeds[{i}].len = 32;"
                    )
                    .unwrap();
                }
            }
            IdlSeed::Arg { path } => {
                writeln!(
                    out,
                    "        seeds[{i}].addr = (const uint8_t *)&args->{path}; seeds[{i}].len = \
                     sizeof(args->{path});"
                )
                .unwrap();
            }
        }
    }
    writeln!(out, "        uint8_t bump;").unwrap();
    writeln!(
        out,
        "        find_program_address(seeds, {seed_count}, (Pubkey *)&{upper_prefix}_PROGRAM_ID, \
         &pda_keys[{pda_idx}], &bump);"
    )
    .unwrap();
    writeln!(out, "    }}").unwrap();
}

fn emit_error_codes(out: &mut String, prefix: &str, errors: &[crate::types::IdlError]) {
    if errors.is_empty() {
        return;
    }
    let upper = prefix.to_ascii_uppercase();
    for err in errors {
        let name = err.name.to_ascii_uppercase();
        writeln!(out, "#define {upper}_ERR_{name} {code}", code = err.code).unwrap();
    }
    out.push('\n');
}

fn c_type(ty: &IdlType, prefix: &str) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => "bool".into(),
            "u8" => "uint8_t".into(),
            "i8" => "int8_t".into(),
            "u16" => "uint16_t".into(),
            "i16" => "int16_t".into(),
            "u32" => "uint32_t".into(),
            "i32" => "int32_t".into(),
            "u64" => "uint64_t".into(),
            "i64" => "int64_t".into(),
            "u128" | "i128" => "uint8_t".into(),
            "f32" => "float".into(),
            "f64" => "double".into(),
            "pubkey" => "Pubkey".into(),
            "string" => "uint8_t *".into(),
            _ if p.starts_with('[') => "uint8_t".into(),
            _ => "uint8_t *".into(),
        },
        IdlType::Option { option } => c_type(option, prefix),
        IdlType::DynString { .. } => "uint8_t *".into(),
        IdlType::DynVec { .. } => "uint8_t *".into(),
        IdlType::Defined { defined } => {
            format!("{prefix}_{}_t", pascal_to_snake(defined))
        }
    }
}

fn is_fixed_array_type(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Primitive(p) if p.starts_with('['))
}

fn fixed_array_size(ty: &IdlType) -> usize {
    match ty {
        IdlType::Primitive(p) if p.starts_with('[') => {
            super::parse_fixed_array_size(p).unwrap_or(1)
        }
        _ => 1,
    }
}

fn is_128bit(ty: &IdlType) -> bool {
    matches!(ty, IdlType::Primitive(p) if p == "u128" || p == "i128")
}

fn emit_struct_field(out: &mut String, prefix: &str, name: &str, ty: &IdlType) {
    let (is_opt, inner) = match ty {
        IdlType::Option { option } => (true, option.as_ref()),
        other => (false, other),
    };
    if is_opt {
        writeln!(out, "    bool {name}_present;").unwrap();
    }
    if matches!(inner, IdlType::DynString { .. } | IdlType::DynVec { .. }) {
        writeln!(out, "    const uint8_t *{name};").unwrap();
        writeln!(out, "    uint32_t {name}_len;").unwrap();
    } else if is_fixed_array_type(inner) {
        let size = fixed_array_size(inner);
        writeln!(out, "    uint8_t {name}[{size}];").unwrap();
    } else if is_128bit(inner) {
        writeln!(out, "    uint8_t {name}[16];").unwrap();
    } else {
        writeln!(out, "    {} {name};", c_type(inner, prefix)).unwrap();
    }
}

fn static_data_overhead(ty: &IdlType, types: &[IdlTypeDef]) -> usize {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" | "u8" | "i8" => 1,
            "u16" | "i16" => 2,
            "u32" | "i32" | "f32" => 4,
            "u64" | "i64" | "f64" => 8,
            "u128" | "i128" => 16,
            "pubkey" => 32,
            other if other.starts_with('[') => super::parse_fixed_array_size(other).unwrap_or(0),
            _ => 0,
        },
        IdlType::Option { option } => 1 + static_data_overhead(option, types),
        IdlType::Defined { defined } => types
            .iter()
            .find(|t| t.name == *defined)
            .map(|td| {
                td.ty
                    .fields
                    .iter()
                    .map(|f| static_data_overhead(&f.ty, types))
                    .sum()
            })
            .unwrap_or(0),
        IdlType::DynString { ref string } => string.prefix_bytes,
        IdlType::DynVec { ref vec } => vec.prefix_bytes,
    }
}

fn serialize_dyn_bytes(name: &str, prefix_bytes: usize, t: &str) -> String {
    let pb = prefix_bytes;
    let write_prefix = match prefix_bytes {
        1 => format!("{t}data_buf[off++] = (uint8_t){name}_len;\n"),
        2 => format!(
            "{t}{{ uint16_t slen = (uint16_t){name}_len; data_buf[off] = (uint8_t)slen; \
             data_buf[off+1] = (uint8_t)(slen >> 8); off += 2; }}\n"
        ),
        4 => format!(
            "{t}{{ uint32_t slen = {name}_len; data_buf[off] = (uint8_t)slen; data_buf[off+1] = \
             (uint8_t)(slen >> 8); data_buf[off+2] = (uint8_t)(slen >> 16); data_buf[off+3] = \
             (uint8_t)(slen >> 24); off += 4; }}\n"
        ),
        _ => format!(
            "{t}{{ uint64_t slen = (uint64_t){name}_len; for (int i = 0; i < 8; i++) {{ \
             data_buf[off + i] = (uint8_t)(slen >> (i * 8)); }} off += 8; }}\n"
        ),
    };
    format!(
        "{t}if (off + {pb} + {name}_len > data_buf_len) return 0;\n{write_prefix}{t}for (uint32_t \
         i = 0; i < {name}_len; i++) data_buf[off++] = {name}[i];\n"
    )
}

fn decode_dyn_bytes(name: &str, prefix_bytes: usize, t: &str) -> String {
    match prefix_bytes {
        1 => format!(
            "{t}out->{name}_len = data[offset]; offset += 1;\n{t}out->{name} = &data[offset]; \
             offset += out->{name}_len;\n"
        ),
        2 => format!(
            "{t}out->{name}_len = (uint32_t)((uint16_t)data[offset] | ((uint16_t)data[offset+1] \
             << 8)); offset += 2;\n{t}out->{name} = &data[offset]; offset += out->{name}_len;\n"
        ),
        4 => format!(
            "{t}out->{name}_len = (uint32_t)data[offset] | ((uint32_t)data[offset+1] << 8) | \
             ((uint32_t)data[offset+2] << 16) | ((uint32_t)data[offset+3] << 24); offset += \
             4;\n{t}out->{name} = &data[offset]; offset += out->{name}_len;\n"
        ),
        _ => format!(
            "{t}{{ uint64_t dlen = 0; for (int i = 0; i < 8; i++) dlen |= \
             ((uint64_t)data[offset+i]) << (i*8); offset += 8; out->{name}_len = (uint32_t)dlen; \
             out->{name} = &data[offset]; offset += out->{name}_len; }}\n"
        ),
    }
}

fn serialize_field_expr(name: &str, ty: &IdlType, types: &[IdlTypeDef], indent: usize) -> String {
    let t = "    ".repeat(indent);
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}data_buf[off++] = {name} ? 1 : 0;\n"),
            "u8" => format!("{t}data_buf[off++] = {name};\n"),
            "i8" => format!("{t}data_buf[off++] = (uint8_t){name};\n"),
            "u16" => format!(
                "{t}{{ uint16_t v = {name}; data_buf[off] = (uint8_t)v; data_buf[off+1] = \
                 (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "i16" => format!(
                "{t}{{ uint16_t v = (uint16_t){name}; data_buf[off] = (uint8_t)v; data_buf[off+1] \
                 = (uint8_t)(v >> 8); off += 2; }}\n"
            ),
            "u32" | "f32" => {
                let cast = if p == "f32" {
                    "uint32_t v; {{ union {{ float f; uint32_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else {
                    format!("uint32_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} data_buf[off] = (uint8_t)v; data_buf[off+1] = (uint8_t)(v >> \
                     8); data_buf[off+2] = (uint8_t)(v >> 16); data_buf[off+3] = (uint8_t)(v >> \
                     24); off += 4; }}\n"
                )
            }
            "u64" | "i64" | "f64" => {
                let cast = if p == "f64" {
                    "uint64_t v; {{ union {{ double f; uint64_t u; }} c; c.f = NAME; v = c.u; }}"
                        .replace("NAME", name)
                } else if p == "i64" {
                    format!("uint64_t v = (uint64_t){name};")
                } else {
                    format!("uint64_t v = {name};")
                };
                format!(
                    "{t}{{ {cast} for (int i = 0; i < 8; i++) {{ data_buf[off + i] = (uint8_t)(v \
                     >> (i * 8)); }} off += 8; }}\n"
                )
            }
            "u128" | "i128" => format!(
                "{t}for (int i = 0; i < 16; i++) data_buf[off + i] = {name}[i]; off += 16;\n"
            ),
            "pubkey" => format!(
                "{t}for (int i = 0; i < 32; i++) data_buf[off + i] = {name}.bytes[i]; off += 32;\n"
            ),
            other if other.starts_with('[') => {
                let size = super::parse_fixed_array_size(other).unwrap_or(1);
                format!(
                    "{t}for (int i = 0; i < {size}; i++) data_buf[off + i] = {name}[i]; off += \
                     {size};\n"
                )
            }
            _ => format!("{t}/* unsupported type for {name} */\n"),
        },
        IdlType::Option { option } => {
            let ti = "    ".repeat(indent + 1);
            let inner = serialize_field_expr(name, option, types, indent + 1);
            format!(
                "{t}if ({name}_present) {{\n{ti}data_buf[off++] = 1;\n{inner}{t}}} else \
                 {{\n{ti}data_buf[off++] = 0;\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == *defined) {
                let mut result = String::new();
                for field in &td.ty.fields {
                    result.push_str(&serialize_field_expr(
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        types,
                        indent,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {defined} */\n")
            }
        }
        IdlType::DynString { ref string } => serialize_dyn_bytes(name, string.prefix_bytes, &t),
        IdlType::DynVec { ref vec } => serialize_dyn_bytes(name, vec.prefix_bytes, &t),
    }
}

fn decode_field_expr(name: &str, ty: &IdlType, depth: usize, types: &[IdlTypeDef]) -> String {
    let t = "    ".repeat(depth);
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!("{t}out->{name} = data[offset] != 0; offset += 1;\n"),
            "u8" => format!("{t}out->{name} = data[offset]; offset += 1;\n"),
            "i8" => format!("{t}out->{name} = (int8_t)data[offset]; offset += 1;\n"),
            "u16" => format!(
                "{t}out->{name} = (uint16_t)data[offset] | ((uint16_t)data[offset + 1] << 8); \
                 offset += 2;\n"
            ),
            "i16" => format!(
                "{t}out->{name} = (int16_t)((uint16_t)data[offset] | ((uint16_t)data[offset + 1] \
                 << 8)); offset += 2;\n"
            ),
            "u32" => format!(
                "{t}out->{name} = (uint32_t)data[offset] | ((uint32_t)data[offset + 1] << 8) | \
                 ((uint32_t)data[offset + 2] << 16) | ((uint32_t)data[offset + 3] << 24); offset \
                 += 4;\n"
            ),
            "i32" => format!(
                "{t}out->{name} = (int32_t)((uint32_t)data[offset] | ((uint32_t)data[offset + 1] \
                 << 8) | ((uint32_t)data[offset + 2] << 16) | ((uint32_t)data[offset + 3] << \
                 24)); offset += 4;\n"
            ),
            "u64" => format!(
                "{t}{{ uint64_t v = 0; for (int i = 0; i < 8; i++) v |= ((uint64_t)data[offset + \
                 i]) << (i * 8); out->{name} = v; offset += 8; }}\n"
            ),
            "i64" => format!(
                "{t}{{ uint64_t v = 0; for (int i = 0; i < 8; i++) v |= ((uint64_t)data[offset + \
                 i]) << (i * 8); out->{name} = (int64_t)v; offset += 8; }}\n"
            ),
            "f32" => format!(
                "{t}{{ union {{ uint32_t u; float f; }} c; c.u = (uint32_t)data[offset] | \
                 ((uint32_t)data[offset+1] << 8) | ((uint32_t)data[offset+2] << 16) | \
                 ((uint32_t)data[offset+3] << 24); out->{name} = c.f; offset += 4; }}\n"
            ),
            "f64" => format!(
                "{t}{{ union {{ uint64_t u; double f; }} c; c.u = 0; for (int i = 0; i < 8; i++) \
                 c.u |= ((uint64_t)data[offset + i]) << (i * 8); out->{name} = c.f; offset += 8; \
                 }}\n"
            ),
            "u128" | "i128" => format!(
                "{t}for (int i = 0; i < 16; i++) out->{name}[i] = data[offset + i]; offset += \
                 16;\n"
            ),
            "pubkey" => format!(
                "{t}for (int i = 0; i < 32; i++) out->{name}.bytes[i] = data[offset + i]; offset \
                 += 32;\n"
            ),
            other if other.starts_with('[') => {
                let size = super::parse_fixed_array_size(other).unwrap_or(1);
                format!(
                    "{t}for (int i = 0; i < {size}; i++) out->{name}[i] = data[offset + i]; \
                     offset += {size};\n"
                )
            }
            _ => format!("{t}/* unsupported decode for {name} */\n"),
        },
        IdlType::Option { option } => {
            let inner = decode_field_expr(name, option, depth + 1, types);
            let ti = "    ".repeat(depth + 1);
            format!(
                "{t}if (data[offset] != 0) {{\n{ti}offset += 1;\n{ti}out->{name}_present = \
                 1;\n{inner}{t}}} else {{\n{ti}offset += 1;\n{ti}out->{name}_present = 0;\n{t}}}\n"
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == *defined) {
                let mut result = String::new();
                for field in &td.ty.fields {
                    result.push_str(&decode_field_expr(
                        &format!("{name}.{f}", f = field.name),
                        &field.ty,
                        depth,
                        types,
                    ));
                }
                result
            } else {
                format!("{t}/* unknown defined type: {defined} */\n")
            }
        }
        IdlType::DynString { ref string } => decode_dyn_bytes(name, string.prefix_bytes, &t),
        IdlType::DynVec { ref vec } => decode_dyn_bytes(name, vec.prefix_bytes, &t),
    }
}
