use {
    super::model::{go_field_path, ProgramModel},
    crate::types::{Idl, IdlType, IdlTypeDef},
    quasar_schema::{snake_to_pascal, to_camel_case},
    std::fmt::Write,
};

/// Generate a Go client package from the IDL.
///
/// Uses `gagliardetto/solana-go` for Solana types (PublicKey, Instruction,
/// AccountMeta).
pub fn generate_go_client(idl: &Idl) -> String {
    let model = ProgramModel::new(idl);
    let pkg_name = model.identity.go_package.clone();
    let mut out = String::new();

    // Package + imports
    writeln!(out, "// Code generated by quasar. DO NOT EDIT.").unwrap();
    writeln!(out, "package {}\n", pkg_name).unwrap();

    let has_events = model.features.has_events;
    let has_args = model.features.has_args;
    let has_types_with_fields = idl.types.iter().any(|t| !t.ty.fields.is_empty());
    let needs_binary = has_args || has_events || has_types_with_fields;
    let has_floats = model.features.has_float;

    out.push_str("import (\n");
    if needs_binary {
        out.push_str("\t\"encoding/binary\"\n");
    }
    if has_events {
        out.push_str("\t\"bytes\"\n");
    }
    if has_floats {
        out.push_str("\t\"math\"\n");
    }
    out.push('\n');
    out.push_str("\tsolana \"github.com/gagliardetto/solana-go\"\n");
    out.push_str(")\n\n");

    // Program ID
    writeln!(
        out,
        "var ProgramID = solana.MustPublicKeyFromBase58(\"{}\")\n",
        idl.address
    )
    .unwrap();

    // Discriminator variables
    for ix in &idl.instructions {
        let name = snake_to_pascal(&ix.name);
        writeln!(
            out,
            "var {}Discriminator = [{}]byte{{{}}}",
            name,
            ix.discriminator.len(),
            super::format_disc_hex(&ix.discriminator),
        )
        .unwrap();
    }
    if !idl.instructions.is_empty() {
        out.push('\n');
    }

    for acc in &idl.accounts {
        let name = snake_to_pascal(&acc.name);
        writeln!(
            out,
            "var {}AccountDiscriminator = [{}]byte{{{}}}",
            name,
            acc.discriminator.len(),
            super::format_disc_hex(&acc.discriminator),
        )
        .unwrap();
    }
    if !idl.accounts.is_empty() {
        out.push('\n');
    }

    for ev in &idl.events {
        let name = snake_to_pascal(&ev.name);
        writeln!(
            out,
            "var {}EventDiscriminator = [{}]byte{{{}}}",
            name,
            ev.discriminator.len(),
            super::format_disc_hex(&ev.discriminator),
        )
        .unwrap();
    }
    if !idl.events.is_empty() {
        out.push('\n');
    }

    // Type definitions (structs)
    for type_def in &idl.types {
        writeln!(out, "type {} struct {{", type_def.name).unwrap();
        for field in &type_def.ty.fields {
            writeln!(
                out,
                "\t{} {}",
                snake_to_pascal(&field.name),
                go_type(&field.ty),
            )
            .unwrap();
        }
        out.push_str("}\n\n");

        // Decode function
        if !type_def.ty.fields.is_empty() {
            writeln!(
                out,
                "func Decode{}(data []byte) *{} {{",
                type_def.name, type_def.name
            )
            .unwrap();
            out.push_str("\toffset := 0\n");
            for field in &type_def.ty.fields {
                out.push_str(&decode_field_expr(
                    &to_camel_case(&field.name),
                    &field.ty,
                    1,
                    &idl.types,
                ));
            }
            let field_assigns: Vec<String> = type_def
                .ty
                .fields
                .iter()
                .map(|f| {
                    let pascal = snake_to_pascal(&f.name);
                    let camel = to_camel_case(&f.name);
                    format!("\t\t{}: {},", pascal, camel)
                })
                .collect();
            writeln!(out, "\treturn &{} {{", type_def.name).unwrap();
            for a in &field_assigns {
                writeln!(out, "{}", a).unwrap();
            }
            out.push_str("\t}\n");
            out.push_str("}\n\n");
        }
    }

    // Instruction input structs + builder functions
    for ix in &idl.instructions {
        let pascal_name = snake_to_pascal(&ix.name);

        // Input struct
        writeln!(out, "type {}Input struct {{", pascal_name).unwrap();
        for acc in &ix.accounts {
            if acc.address.is_some() || acc.pda.is_some() {
                continue;
            }
            writeln!(out, "\t{} solana.PublicKey", snake_to_pascal(&acc.name)).unwrap();
        }
        for arg in &ix.args {
            writeln!(out, "\t{} {}", snake_to_pascal(&arg.name), go_type(&arg.ty),).unwrap();
        }
        if ix.has_remaining {
            out.push_str("\tRemainingAccounts []*solana.AccountMeta\n");
        }
        out.push_str("}\n\n");

        // Builder function
        writeln!(
            out,
            "func New{}Instruction(input *{}Input) *solana.GenericInstruction {{",
            pascal_name, pascal_name,
        )
        .unwrap();

        out.push_str("\taccountsMap := map[string]solana.PublicKey{}\n");

        // Accounts
        out.push_str("\taccounts := []*solana.AccountMeta{}\n");
        for acc in &ix.accounts {
            let key_expr = if let Some(ref addr) = acc.address {
                format!("solana.MustPublicKeyFromBase58(\"{}\")", addr)
            } else if let Some(ref pda) = acc.pda {
                let mut seeds = Vec::new();
                for seed in &pda.seeds {
                    match seed {
                        crate::types::IdlSeed::Const { value } => {
                            seeds.push(format!("[]byte{{{}}}", super::format_disc_hex(value)));
                        }
                        crate::types::IdlSeed::Account { path } => {
                            seeds.push(format!(
                                "func() []byte {{ key := accountsMap[\"{}\"]; return key[:] }}()",
                                path
                            ));
                        }
                        crate::types::IdlSeed::Arg { path } => {
                            seeds.push(format!("input.{}", go_field_path(path)));
                        }
                    }
                }
                // PDA derivation inline — panic on error (invalid seeds = programmer error)
                format!(
                    "func() solana.PublicKey {{ addr, _, err := \
                     solana.FindProgramAddress([][]byte{{{}}}, ProgramID); if err != nil {{ \
                     panic(err) }}; return addr }}()",
                    seeds.join(", ")
                )
            } else {
                format!("input.{}", snake_to_pascal(&acc.name))
            };

            writeln!(out, "\taccountsMap[\"{}\"] = {}", acc.name, key_expr).unwrap();
            let meta_expr = account_meta_expr(
                &format!("accountsMap[\"{}\"]", acc.name),
                acc.signer,
                acc.writable,
            );
            writeln!(out, "\taccounts = append(accounts, {})", meta_expr).unwrap();
        }

        if ix.has_remaining {
            out.push_str("\taccounts = append(accounts, input.RemainingAccounts...)\n");
        }

        // Data — compact wire format:
        //   [disc][fixed fields][all dynamic prefixes][all dynamic data]
        let disc_var = format!("{}Discriminator", pascal_name);
        let has_dyn = ix.args.iter().any(|a| is_direct_dynamic(&a.ty));
        if ix.args.is_empty() {
            writeln!(out, "\tdata := {}[:]", disc_var).unwrap();
        } else if !has_dyn {
            // Fixed-only path: simple inline serialisation.
            writeln!(out, "\tdata := make([]byte, 0, 256)").unwrap();
            writeln!(out, "\tdata = append(data, {}[:]...)", disc_var).unwrap();
            for arg in &ix.args {
                out.push_str(&serialize_field_expr(
                    &snake_to_pascal(&arg.name),
                    &arg.ty,
                    &idl.types,
                ));
            }
        } else {
            // Compact 3-phase encoding.
            let fixed_args: Vec<_> = ix
                .args
                .iter()
                .filter(|a| !is_direct_dynamic(&a.ty))
                .collect();
            let dyn_args: Vec<_> = ix
                .args
                .iter()
                .filter(|a| is_direct_dynamic(&a.ty))
                .collect();

            writeln!(out, "\tdata := make([]byte, 0, 256)").unwrap();
            writeln!(out, "\tdata = append(data, {}[:]...)", disc_var).unwrap();

            // Phase 1: fixed fields
            for arg in &fixed_args {
                out.push_str(&serialize_field_expr(
                    &snake_to_pascal(&arg.name),
                    &arg.ty,
                    &idl.types,
                ));
            }

            // Phase 2: length table — pre-encode dynamic slices and emit all
            // length prefixes grouped together.
            for arg in &dyn_args {
                let name = snake_to_pascal(&arg.name);
                match &arg.ty {
                    IdlType::DynString { ref string } => {
                        // Pre-encode string bytes so we know the length.
                        writeln!(out, "\t_{n}Bytes := []byte(input.{n})", n = name,).unwrap();
                        match string.prefix_bytes {
                            1 => writeln!(
                                out,
                                "\tdata = append(data, byte(len(_{n}Bytes)))",
                                n = name,
                            )
                            .unwrap(),
                            2 => writeln!(
                                out,
                                "\t{{ var _buf [2]byte; binary.LittleEndian.PutUint16(_buf[:], \
                                 uint16(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                            4 => writeln!(
                                out,
                                "\t{{ var _buf [4]byte; binary.LittleEndian.PutUint32(_buf[:], \
                                 uint32(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                            _ => writeln!(
                                out,
                                "\t{{ var _buf [8]byte; binary.LittleEndian.PutUint64(_buf[:], \
                                 uint64(len(_{n}Bytes))); data = append(data, _buf[:]...) }}",
                                n = name,
                            )
                            .unwrap(),
                        }
                    }
                    IdlType::DynVec { ref vec } => match vec.prefix_bytes {
                        1 => {
                            writeln!(out, "\tdata = append(data, byte(len(input.{n})))", n = name,)
                                .unwrap()
                        }
                        2 => writeln!(
                            out,
                            "\t{{ var _buf [2]byte; binary.LittleEndian.PutUint16(_buf[:], \
                             uint16(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                        4 => writeln!(
                            out,
                            "\t{{ var _buf [4]byte; binary.LittleEndian.PutUint32(_buf[:], \
                             uint32(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                        _ => writeln!(
                            out,
                            "\t{{ var _buf [8]byte; binary.LittleEndian.PutUint64(_buf[:], \
                             uint64(len(input.{n}))); data = append(data, _buf[:]...) }}",
                            n = name,
                        )
                        .unwrap(),
                    },
                    _ => unreachable!(),
                }
            }

            // Phase 3: tail data
            for arg in &dyn_args {
                let name = snake_to_pascal(&arg.name);
                match &arg.ty {
                    IdlType::DynString { .. } => {
                        writeln!(out, "\tdata = append(data, _{n}Bytes...)", n = name,).unwrap();
                    }
                    IdlType::DynVec { .. } => {
                        writeln!(out, "\tdata = append(data, input.{n}...)", n = name,).unwrap();
                    }
                    _ => unreachable!(),
                }
            }
        }

        out.push_str("\treturn solana.NewInstruction(ProgramID, accounts, data)\n");
        out.push_str("}\n\n");
    }

    // Event decoder
    if has_events {
        out.push_str("type DecodedEvent struct {\n");
        out.push_str("\tName string\n");
        out.push_str("\tData interface{}\n");
        out.push_str("}\n\n");

        out.push_str("func DecodeEvent(data []byte) *DecodedEvent {\n");
        for ev in &idl.events {
            let name = snake_to_pascal(&ev.name);
            let disc_len = ev.discriminator.len();
            let type_def = idl.types.iter().find(|t| t.name == ev.name);
            writeln!(
                out,
                "\tif len(data) >= {} && bytes.Equal(data[:{}], {}EventDiscriminator[:]) {{",
                disc_len, disc_len, name,
            )
            .unwrap();
            if let Some(td) = type_def {
                if td.ty.fields.is_empty() {
                    writeln!(
                        out,
                        "\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}",
                        ev.name
                    )
                    .unwrap();
                } else {
                    writeln!(
                        out,
                        "\t\treturn &DecodedEvent{{Name: \"{}\", Data: Decode{}(data[{}:])}}",
                        ev.name, ev.name, disc_len,
                    )
                    .unwrap();
                }
            } else {
                writeln!(
                    out,
                    "\t\treturn &DecodedEvent{{Name: \"{}\", Data: nil}}",
                    ev.name
                )
                .unwrap();
            }
            out.push_str("\t}\n");
        }
        out.push_str("\treturn nil\n");
        out.push_str("}\n\n");
    }

    out
}

pub fn generate_go_mod_for_program(model: &ProgramModel<'_>) -> String {
    generate_go_mod(&model.identity.go_package)
}

/// Generate go.mod content.
pub fn generate_go_mod(module_name: &str) -> String {
    format!(
        r#"module {}

go 1.21

require github.com/gagliardetto/solana-go v1.12.0
"#,
        module_name,
    )
}

// ---------------------------------------------------------------------------
// Type mapping
// ---------------------------------------------------------------------------

fn go_type(ty: &IdlType) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => "bool".to_string(),
            "u8" => "uint8".to_string(),
            "i8" => "int8".to_string(),
            "u16" => "uint16".to_string(),
            "i16" => "int16".to_string(),
            "u32" => "uint32".to_string(),
            "i32" => "int32".to_string(),
            "u64" => "uint64".to_string(),
            "i64" => "int64".to_string(),
            "u128" => "[16]byte".to_string(),
            "i128" => "[16]byte".to_string(),
            "f32" => "float32".to_string(),
            "f64" => "float64".to_string(),
            "pubkey" => "solana.PublicKey".to_string(),
            "string" => "string".to_string(),
            other if other.starts_with('[') => {
                let size = super::parse_fixed_array_size(other).unwrap_or(1);
                format!("[{}]byte", size)
            }
            _ => "[]byte".to_string(),
        },
        IdlType::Option { option } => format!("*{}", go_type(option)),
        IdlType::DynString { .. } => "string".to_string(),
        IdlType::DynVec { .. } => "[]byte".to_string(),
        IdlType::Defined { defined } => defined.clone(),
    }
}

// ---------------------------------------------------------------------------
// Account meta helpers
// ---------------------------------------------------------------------------

fn account_meta_expr(key_expr: &str, signer: bool, writable: bool) -> String {
    let mut s = format!("solana.Meta({})", key_expr);
    if writable {
        s.push_str(".WRITE()");
    }
    if signer {
        s.push_str(".SIGNER()");
    }
    s
}

// ---------------------------------------------------------------------------
// Serialization
// ---------------------------------------------------------------------------

/// Returns `true` if the type is a top-level dynamic type (`DynString` or
/// `DynVec`). These require compact 3-phase encoding at the instruction level.
fn is_direct_dynamic(ty: &IdlType) -> bool {
    matches!(ty, IdlType::DynString { .. } | IdlType::DynVec { .. })
}

fn serialize_field_expr(name: &str, ty: &IdlType, types: &[IdlTypeDef]) -> String {
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "\tif input.{n} {{\n\t\tdata = append(data, 1)\n\t}} else {{\n\t\tdata = \
                 append(data, 0)\n\t}}\n",
                n = name,
            ),
            "u8" => format!("\tdata = append(data, input.{})\n", name),
            "i8" => format!("\tdata = append(data, byte(input.{}))\n", name),
            "u16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i16" => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], uint16(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], uint32(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], input.{n}); data = \
                 append(data, buf[:]...) }}\n",
                n = name,
            ),
            "i64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], uint64(input.{n})); \
                 data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "u128" | "i128" => format!("\tdata = append(data, input.{}[:]...)\n", name,),
            "f32" => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], \
                 math.Float32bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "f64" => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], \
                 math.Float64bits(input.{n})); data = append(data, buf[:]...) }}\n",
                n = name,
            ),
            "pubkey" => format!("\tdata = append(data, input.{}[:]...)\n", name,),
            "string" => format!(
                "\t{{ b := []byte(input.{n}); var buf [4]byte; \
                 binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = append(data, \
                 buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
            _ if p.starts_with('[') => {
                format!("\tdata = append(data, input.{}[:]...)\n", name)
            }
            _ => format!("\tdata = append(data, input.{}...)\n", name),
        },
        IdlType::DynString { ref string } => match string.prefix_bytes {
            1 => format!(
                "\tdata = append(data, byte(len([]byte(input.{n}))))\n\tdata = append(data, \
                 []byte(input.{n})...)\n",
                n = name,
            ),
            2 => format!(
                "\t{{ b := []byte(input.{n}); var buf [2]byte; \
                 binary.LittleEndian.PutUint16(buf[:], uint16(len(b))); data = append(data, \
                 buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
            4 => format!(
                "\t{{ b := []byte(input.{n}); var buf [4]byte; \
                 binary.LittleEndian.PutUint32(buf[:], uint32(len(b))); data = append(data, \
                 buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
            _ => format!(
                "\t{{ b := []byte(input.{n}); var buf [8]byte; \
                 binary.LittleEndian.PutUint64(buf[:], uint64(len(b))); data = append(data, \
                 buf[:]...); data = append(data, b...) }}\n",
                n = name,
            ),
        },
        IdlType::Option { option } => {
            let inner = serialize_field_expr(&format!("(*input.{})", name), option, types);
            format!(
                "\tif input.{n} == nil {{\n\t\tdata = append(data, 0)\n\t}} else {{\n\t\tdata = \
                 append(data, 1)\n{inner}\t}}\n",
                n = name,
                inner = inner,
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == *defined) {
                let mut result = String::new();
                for field in &td.ty.fields {
                    result.push_str(&serialize_field_expr(
                        &format!("{}.{}", name, snake_to_pascal(&field.name)),
                        &field.ty,
                        types,
                    ));
                }
                result
            } else {
                format!("\tdata = append(data, input.{}...)\n", name)
            }
        }
        IdlType::DynVec { vec } => match vec.prefix_bytes {
            1 => format!(
                "\tdata = append(data, byte(len(input.{n})))\n\tdata = append(data, \
                 input.{n}...)\n",
                n = name,
            ),
            2 => format!(
                "\t{{ var buf [2]byte; binary.LittleEndian.PutUint16(buf[:], \
                 uint16(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                 input.{n}...) }}\n",
                n = name,
            ),
            4 => format!(
                "\t{{ var buf [4]byte; binary.LittleEndian.PutUint32(buf[:], \
                 uint32(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                 input.{n}...) }}\n",
                n = name,
            ),
            _ => format!(
                "\t{{ var buf [8]byte; binary.LittleEndian.PutUint64(buf[:], \
                 uint64(len(input.{n}))); data = append(data, buf[:]...); data = append(data, \
                 input.{n}...) }}\n",
                n = name,
            ),
        },
    }
}

/// Go float decode expression. Extracted to prevent rustfmt from splitting
/// the `\n` in the format string across a line continuation.
fn go_float_decode(t: &str, n: &str, math_fn: &str, le_fn: &str, size: usize) -> String {
    format!(
        "{t}{n} := math.{math_fn}(binary.LittleEndian.{le_fn}(data[offset:]))\n{t}offset += \
         {size}\n"
    )
}

// ---------------------------------------------------------------------------
// Deserialization
// ---------------------------------------------------------------------------

fn decode_field_expr(name: &str, ty: &IdlType, depth: usize, types: &[IdlTypeDef]) -> String {
    let t = "\t".repeat(depth);
    match ty {
        IdlType::Primitive(p) => match p.as_str() {
            "bool" => format!(
                "{t}{n} := data[offset] != 0\n{t}offset += 1\n",
                t = t,
                n = name,
            ),
            "u8" => format!("{t}{n} := data[offset]\n{t}offset += 1\n", t = t, n = name,),
            "i8" => format!(
                "{t}{n} := int8(data[offset])\n{t}offset += 1\n",
                t = t,
                n = name,
            ),
            "u16" => format!(
                "{t}{n} := binary.LittleEndian.Uint16(data[offset:])\n{t}offset += 2\n",
                t = t,
                n = name,
            ),
            "i16" => format!(
                "{t}{n} := int16(binary.LittleEndian.Uint16(data[offset:]))\n{t}offset += 2\n",
                t = t,
                n = name,
            ),
            "u32" => format!(
                "{t}{n} := binary.LittleEndian.Uint32(data[offset:])\n{t}offset += 4\n",
                t = t,
                n = name,
            ),
            "i32" => format!(
                "{t}{n} := int32(binary.LittleEndian.Uint32(data[offset:]))\n{t}offset += 4\n",
                t = t,
                n = name,
            ),
            "u64" => format!(
                "{t}{n} := binary.LittleEndian.Uint64(data[offset:])\n{t}offset += 8\n",
                t = t,
                n = name,
            ),
            "i64" => format!(
                "{t}{n} := int64(binary.LittleEndian.Uint64(data[offset:]))\n{t}offset += 8\n",
                t = t,
                n = name,
            ),
            "u128" | "i128" => format!(
                "{t}var {n} [16]byte\n{t}copy({n}[:], data[offset:offset+16])\n{t}offset += 16\n",
                t = t,
                n = name,
            ),
            "f32" => go_float_decode(&t, name, "Float32frombits", "Uint32", 4),
            "f64" => go_float_decode(&t, name, "Float64frombits", "Uint64", 8),
            "pubkey" => format!(
                "{t}var {n} solana.PublicKey\n{t}copy({n}[:], data[offset:offset+32])\n{t}offset \
                 += 32\n",
                t = t,
                n = name,
            ),
            _ if p.starts_with('[') => {
                let size = super::parse_fixed_array_size(p).unwrap_or(1);
                format!(
                    "{t}var {n} [{sz}]byte\n{t}copy({n}[:], data[offset:offset+{sz}])\n{t}offset \
                     += {sz}\n",
                    t = t,
                    n = name,
                    sz = size,
                )
            }
            _ => format!(
                "{t}{n} := data[offset:] // unsupported type\n{t}_ = {n}\n",
                t = t,
                n = name,
            ),
        },
        IdlType::DynString { ref string } => match string.prefix_bytes {
            1 => format!(
                "{t}{n}Len := int(data[offset])\n{t}offset += 1\n{t}{n} := \
                 string(data[offset:offset+{n}Len])\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            2 => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint16(data[offset:]))\n{t}offset += \
                 2\n{t}{n} := string(data[offset:offset+{n}Len])\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            4 => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint32(data[offset:]))\n{t}offset += \
                 4\n{t}{n} := string(data[offset:offset+{n}Len])\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            _ => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint64(data[offset:]))\n{t}offset += \
                 8\n{t}{n} := string(data[offset:offset+{n}Len])\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
        },
        IdlType::Option { option } => {
            let inner = decode_field_expr(&format!("{}_val", name), option, depth, types);
            format!(
                "{t}var {n} *{ty}\n{t}if data[offset] != 0 {{\n{t}\toffset += 1\n{inner}{t}\t{n} \
                 = &{n}_val\n{t}}} else {{\n{t}\toffset += 1\n{t}}}\n",
                t = t,
                n = name,
                ty = go_type(option),
                inner = inner,
            )
        }
        IdlType::Defined { defined } => {
            if let Some(td) = types.iter().find(|t| t.name == *defined) {
                let mut result = String::new();
                for field in &td.ty.fields {
                    result.push_str(&decode_field_expr(
                        &to_camel_case(&field.name),
                        &field.ty,
                        depth,
                        types,
                    ));
                }
                let field_assigns: Vec<String> = td
                    .ty
                    .fields
                    .iter()
                    .map(|f| format!("{}: {},", snake_to_pascal(&f.name), to_camel_case(&f.name)))
                    .collect();
                result.push_str(&format!(
                    "{t}{n} := {cls}{{\n",
                    t = t,
                    n = name,
                    cls = defined
                ));
                for a in &field_assigns {
                    result.push_str(&format!("{t}\t{a}\n", t = t, a = a));
                }
                result.push_str(&format!("{t}}}\n", t = t));
                result
            } else {
                format!(
                    "{t}{n} := data[offset:] // unknown type\n{t}_ = {n}\n",
                    t = t,
                    n = name,
                )
            }
        }
        IdlType::DynVec { vec } => match vec.prefix_bytes {
            1 => format!(
                "{t}{n}Len := int(data[offset])\n{t}offset += 1\n{t}{n} := \
                 data[offset:offset+{n}Len]\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            2 => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint16(data[offset:]))\n{t}offset += \
                 2\n{t}{n} := data[offset:offset+{n}Len]\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            4 => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint32(data[offset:]))\n{t}offset += \
                 4\n{t}{n} := data[offset:offset+{n}Len]\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
            _ => format!(
                "{t}{n}Len := int(binary.LittleEndian.Uint64(data[offset:]))\n{t}offset += \
                 8\n{t}{n} := data[offset:offset+{n}Len]\n{t}offset += {n}Len\n",
                t = t,
                n = name,
            ),
        },
    }
}
